plugins {
    id 'com.android.application'
}

android {
    namespace 'com.codex.brownnoisetimer'
    compileSdk 36

    defaultConfig {
        applicationId 'com.codex.brownnoisetimer'
        minSdk 26
        targetSdk 36
        versionCode 4
        versionName '1.2.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
